# Generated by Django 4.2.27 on 2026-01-07 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_customer_store_custo_last_na_e6a359_idx_and_more'),
    ]

    operations = [
    ]
